# Over-the-Air update. Use this when you have JS-only changes that don't require a full native build.
name: 'OTA Update'
on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Which platform to build for
        options:
          - ios
          - android
        required: true
      environment:
        type: choice
        description: Which env to build for
        options:
          - test
          - stag
          - prod
        required: true
        default: test
      ota-message:
        type: string
        description: OTA message to include in the OTA update
        required: true
      ota-branch:
        type: string
        description: OTA branch (should correspond to the app version)
        required: true
        default: version-1.0.0
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Setup repo
        uses: actions/checkout@v3

      - name: â” Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: ./package.json

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸŒ Compile translations
        run: npm run i18n:extract && npm run i18n:compile

      - name: ğŸš€ Create update
        run: eas update --channel ${{ inputs.environment }} --message ${{ inputs.ota-message }} --branch ${{ inputs.ota-branch }} --non-interactive

      - name: âœ… Notify slack success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: builds # <-- Change this to the relevant slack channel
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ github.event.organization.avatar_url }}
          SLACK_TITLE: 'Update successfull :white_check_mark:'
          SLACK_MESSAGE: 'See [EAS build](https://expo.dev/accounts/taito-united/projects/taito-template/updates) :rocket:'
          SLACK_USERNAME: ${{ github.event.repository.name }} - ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: âŒ Notify slack fail
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: builds # <-- Change this to the relevant slack channel
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ github.event.organization.avatar_url }}
          SLACK_TITLE: 'Update failed :x:'
          SLACK_MESSAGE: 'See [EAS build](https://expo.dev/accounts/taito-united/projects/taito-template/updates) for more info :sad_pepe:'
          SLACK_USERNAME: ${{ github.event.repository.name }} - ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
